'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArrowUpRight, CircleDollarSign } from 'lucide-react'

type Payable = { id: string; number: string; status: string; originalAmount: string; paidAmount: string; balance: string; dueDate: string; supplier: { name: string; document: string }; purchase: { number: string } }
type Account = { id: string; name: string; balance: string }
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })

export default function PayablesModule() {
  const [payables, setPayables] = useState<Payable[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [selected, setSelected] = useState(''); const [form, setForm] = useState({ cashAccountId: '', paymentMethod: 'CASH', amount: '' }); const [message, setMessage] = useState('')
  async function load() { const [payableResponse, accountResponse] = await Promise.all([fetch('/api/payables'), fetch('/api/cash')]); setPayables(await payableResponse.json()); const accountData = await accountResponse.json(); setAccounts(accountData); setForm((current) => ({ ...current, cashAccountId: current.cashAccountId || accountData[0]?.id || '' })) }
  useEffect(() => { void load() }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch('/api/payables', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, payableId: selected }) }); const data = await response.json(); setMessage(response.ok ? `Pago ${data.reference} registrado.` : data.error); if (response.ok) { setSelected(''); setForm((current) => ({ ...current, amount: '' })); await load() } }
  const pending = payables.filter((item) => item.status !== 'PAID').reduce((sum, item) => sum + Number(item.balance), 0)
  return <div className="dashboard-content"><div className="page-heading"><div><p className="eyebrow">Finanzas · Bolivia</p><h1>Cuentas por pagar</h1><p className="muted">Obligaciones con proveedores en USD.</p></div><span className="currency-note">Pendiente: {money.format(pending)}</span></div>{message && <p className="module-message">{message}</p>}<form className="panel product-form" onSubmit={submit}><div className="product-form-grid"><label>Obligación<select required value={selected} onChange={(event) => { setSelected(event.target.value); const item = payables.find((row) => row.id === event.target.value); setForm((current) => ({ ...current, amount: item?.balance ?? '' })) }}><option value="">Selecciona una obligación</option>{payables.filter((item) => item.status !== 'PAID').map((item) => <option key={item.id} value={item.id}>{item.supplier.name} · {money.format(Number(item.balance))}</option>)}</select></label><label>Cuenta de pago<select required value={form.cashAccountId} onChange={(event) => setForm({ ...form, cashAccountId: event.target.value })}><option value="">Selecciona una cuenta</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Medio de pago<select value={form.paymentMethod} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value })}><option value="CASH">Efectivo</option><option value="BANK_TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="QR">QR</option></select></label><label>Monto USD<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></label></div><button className="primary-button" type="submit"><CircleDollarSign size={15} /> Registrar pago</button></form><article className="panel module-table"><div className="table-scroll"><table><thead><tr><th>Proveedor</th><th>Compra</th><th>Vencimiento</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{payables.length === 0 ? <tr><td colSpan={7}>No hay cuentas por pagar.</td></tr> : payables.map((item) => <tr key={item.id}><td><div className="product-cell"><span className="product-thumb"><ArrowUpRight size={16} /></span><div><strong>{item.supplier.name}</strong><small>{item.supplier.document}</small></div></div></td><td>{item.purchase.number}</td><td>{new Date(item.dueDate).toLocaleDateString('es-BO')}</td><td>{money.format(Number(item.originalAmount))}</td><td>{money.format(Number(item.paidAmount))}</td><td><strong>{money.format(Number(item.balance))}</strong></td><td><span className="status warning"><i />{item.status}</span></td></tr>)}</tbody></table></div></article></div>
}
